export const AUTOMATION = {
  id: "task-1",
  thread_id: null,
  context_mode: "fresh_thread_per_run" as const,
  agent_asset_id: "22222222-2222-4222-8222-222222222222",
  agent_scope: "project" as const,
  title: "Daily review",
  prompt: "Review the project.",
  schedule_type: "cron" as const,
  schedule_spec: { cron: "0 9 * * *" },
  timezone: "Asia/Shanghai",
  status: "enabled" as const,
  next_run_at: "2026-07-17T01:00:00Z",
  last_run_at: null,
  last_outcome: null,
  last_error_code: null,
  run_count: 0,
  version: 1,
  created_at: "2026-07-16T00:00:00Z",
  updated_at: "2026-07-16T00:00:00Z",
};

export const AUTOMATION_RUN = {
  id: "occurrence-1",
  automation_id: AUTOMATION.id,
  automation_version: 1,
  scheduled_for: "2026-07-16T01:00:00Z",
  trigger: "manual" as const,
  status: "queued" as const,
  thread_id: null,
  run_id: null,
  error_code: null,
  started_at: null,
  finished_at: null,
  created_at: "2026-07-16T01:00:00Z",
  updated_at: "2026-07-16T01:00:00Z",
};

export const AUTOMATION_READINESS = {
  status: "ready" as const,
  code: "AUTOMATION_READY",
  scheduler_enabled: true,
  scheduler_status: "running" as const,
  project_private_work_ready: true,
  schema_ready: true,
  request_id: "req-ready",
};
