"""ActWeave Knowledge Package public API.

Host adapters must import only from this root module. ORM models,
repositories, the MinIO object store, and provider clients are internal.
"""

from .authority import KnowledgeProjectAuthority
from .contracts import (
    KNOWLEDGE_CONFLICT,
    KNOWLEDGE_DEFAULT_CHILD_CHUNK_SEPARATOR,
    KNOWLEDGE_DEFAULT_CHUNK_SEPARATOR,
    KNOWLEDGE_DISABLED,
    KNOWLEDGE_EMBEDDING_FAILED,
    KNOWLEDGE_FORBIDDEN,
    KNOWLEDGE_INVALID_REQUEST,
    KNOWLEDGE_MAX_METADATA_FIELDS_PER_BASE,
    KNOWLEDGE_MAX_METADATA_FILTERS,
    KNOWLEDGE_MAX_METADATA_NAME_LENGTH,
    KNOWLEDGE_MAX_METADATA_STRING_LENGTH,
    KNOWLEDGE_MAX_TOP_K,
    KNOWLEDGE_MODEL_UNAVAILABLE,
    KNOWLEDGE_NAME_CONFLICT,
    KNOWLEDGE_NOT_FOUND,
    KNOWLEDGE_PARSE_FAILED,
    KNOWLEDGE_QUOTA_EXCEEDED,
    KNOWLEDGE_RERANK_FAILED,
    KNOWLEDGE_SEARCH_FAILED,
    KNOWLEDGE_STORAGE_UNAVAILABLE,
    KNOWLEDGE_TASK_FAILED,
    KnowledgeBaseCreate,
    KnowledgeBaseUpdate,
    KnowledgeBaseView,
    KnowledgeChunkingMode,
    KnowledgeChunkPreview,
    KnowledgeChunkPreviewChunk,
    KnowledgeChunkPreviewRequest,
    KnowledgeCitation,
    KnowledgeDocumentUpload,
    KnowledgeDocumentView,
    KnowledgeEmbeddingMaterial,
    KnowledgeError,
    KnowledgeHealth,
    KnowledgeMetadataFieldType,
    KnowledgeMetadataFieldView,
    KnowledgeMetadataFilter,
    KnowledgeMetadataFilterOperator,
    KnowledgeModelPort,
    KnowledgeModelType,
    KnowledgeQuerySource,
    KnowledgeQueryView,
    KnowledgeRerankMaterial,
    KnowledgeSearchRequest,
    KnowledgeSearchResult,
    KnowledgeSegmentCreate,
    KnowledgeSegmentUpdate,
    KnowledgeSegmentView,
    KnowledgeSettings,
)
from .module import KnowledgeModule, create_knowledge_module
from .project_retention import (
    KnowledgeProjectPurger,
    create_knowledge_project_purger,
)
from .retention import purge_knowledge_query_history

__all__ = [
    "KNOWLEDGE_CONFLICT",
    "KNOWLEDGE_DISABLED",
    "KNOWLEDGE_EMBEDDING_FAILED",
    "KNOWLEDGE_FORBIDDEN",
    "KNOWLEDGE_INVALID_REQUEST",
    "KNOWLEDGE_MODEL_UNAVAILABLE",
    "KNOWLEDGE_NAME_CONFLICT",
    "KNOWLEDGE_NOT_FOUND",
    "KNOWLEDGE_PARSE_FAILED",
    "KNOWLEDGE_QUOTA_EXCEEDED",
    "KNOWLEDGE_RERANK_FAILED",
    "KNOWLEDGE_SEARCH_FAILED",
    "KNOWLEDGE_STORAGE_UNAVAILABLE",
    "KNOWLEDGE_TASK_FAILED",
    "KNOWLEDGE_DEFAULT_CHILD_CHUNK_SEPARATOR",
    "KNOWLEDGE_DEFAULT_CHUNK_SEPARATOR",
    "KNOWLEDGE_MAX_METADATA_FIELDS_PER_BASE",
    "KNOWLEDGE_MAX_METADATA_FILTERS",
    "KNOWLEDGE_MAX_METADATA_NAME_LENGTH",
    "KNOWLEDGE_MAX_METADATA_STRING_LENGTH",
    "KNOWLEDGE_MAX_TOP_K",
    "KnowledgeBaseCreate",
    "KnowledgeBaseUpdate",
    "KnowledgeBaseView",
    "KnowledgeChunkingMode",
    "KnowledgeChunkPreview",
    "KnowledgeChunkPreviewChunk",
    "KnowledgeChunkPreviewRequest",
    "KnowledgeCitation",
    "KnowledgeDocumentUpload",
    "KnowledgeDocumentView",
    "KnowledgeEmbeddingMaterial",
    "KnowledgeError",
    "KnowledgeHealth",
    "KnowledgeMetadataFieldType",
    "KnowledgeMetadataFieldView",
    "KnowledgeMetadataFilter",
    "KnowledgeMetadataFilterOperator",
    "KnowledgeModelPort",
    "KnowledgeModelType",
    "KnowledgeModule",
    "KnowledgeProjectPurger",
    "KnowledgeProjectAuthority",
    "KnowledgeQuerySource",
    "KnowledgeQueryView",
    "KnowledgeRerankMaterial",
    "KnowledgeSearchRequest",
    "KnowledgeSearchResult",
    "KnowledgeSegmentCreate",
    "KnowledgeSegmentUpdate",
    "KnowledgeSegmentView",
    "KnowledgeSettings",
    "create_knowledge_module",
    "create_knowledge_project_purger",
    "purge_knowledge_query_history",
]
