"""Operator-only encrypted PostgreSQL recovery archive primitives."""

from .archive import (
    ARCHIVE_FORMAT_VERSION,
    CHUNK_SIZE,
    MAX_ARCHIVE_CHUNKS,
    MAX_ARCHIVE_PLAINTEXT_BYTES,
    MAX_MANIFEST_BYTES,
    BackupArchiveReader,
    BackupArchiveWriter,
    BackupAuthenticationFailed,
    BackupCommandFailed,
    BackupConfig,
    BackupKeyInvalid,
    BackupKeyMissing,
    BackupManifest,
    BackupSnapshot,
    create_backup,
    load_backup_key,
    pg_dump_argv,
)

__all__ = [
    "ARCHIVE_FORMAT_VERSION",
    "CHUNK_SIZE",
    "MAX_ARCHIVE_CHUNKS",
    "MAX_ARCHIVE_PLAINTEXT_BYTES",
    "MAX_MANIFEST_BYTES",
    "BackupArchiveReader",
    "BackupArchiveWriter",
    "BackupAuthenticationFailed",
    "BackupCommandFailed",
    "BackupConfig",
    "BackupKeyInvalid",
    "BackupKeyMissing",
    "BackupManifest",
    "BackupSnapshot",
    "create_backup",
    "load_backup_key",
    "pg_dump_argv",
]
