"""Workflow compiler IR, topology validation, and bounded compile cache."""

from deerflow.workflows.compiler.cache import (
    CompilerCacheKey,
    WorkflowCompilerCache,
)
from deerflow.workflows.compiler.core import (
    COMPILER_CONTRACT_VERSION_V1,
    CURRENT_COMPILER_CONTRACT_VERSION,
    GRAPH_SCHEMA_VERSION_V1,
    WorkflowCompilerContract,
    WorkflowCompilerUnavailableError,
    compile_workflow,
    require_compiler_contract,
)
from deerflow.workflows.compiler.ir import (
    WORKFLOW_VALUE_MISSING,
    CompiledAggregate,
    CompiledAggregateGroup,
    CompiledBranch,
    CompiledBranchRoute,
    CompiledEdge,
    CompiledEndpoint,
    CompiledLoopRegion,
    CompiledLoopVariable,
    CompiledNode,
    CompiledPort,
    CompiledTransform,
    CompiledValueType,
    CompiledWorkflowOutput,
    FrozenObject,
    StructuredLoopPlan,
    StructuredLoopTemplate,
    WorkflowIR,
    WorkflowOutputSettlementError,
    freeze_json,
    lower_structured_loop,
    settle_workflow_outputs,
    thaw_json,
    workflow_ir_public_projection_v1,
)
from deerflow.workflows.compiler.topology import (
    AuthoredDag,
    WorkflowTopology,
    WorkflowTopologyError,
    analyze_workflow_topology,
)

__all__ = [
    "AuthoredDag",
    "COMPILER_CONTRACT_VERSION_V1",
    "CURRENT_COMPILER_CONTRACT_VERSION",
    "CompilerCacheKey",
    "CompiledAggregate",
    "CompiledAggregateGroup",
    "CompiledBranch",
    "CompiledBranchRoute",
    "CompiledEdge",
    "CompiledEndpoint",
    "CompiledLoopRegion",
    "CompiledLoopVariable",
    "CompiledNode",
    "CompiledPort",
    "CompiledTransform",
    "CompiledValueType",
    "CompiledWorkflowOutput",
    "FrozenObject",
    "GRAPH_SCHEMA_VERSION_V1",
    "WORKFLOW_VALUE_MISSING",
    "StructuredLoopPlan",
    "StructuredLoopTemplate",
    "WorkflowCompilerCache",
    "WorkflowCompilerContract",
    "WorkflowCompilerUnavailableError",
    "WorkflowIR",
    "WorkflowOutputSettlementError",
    "WorkflowTopology",
    "WorkflowTopologyError",
    "analyze_workflow_topology",
    "compile_workflow",
    "freeze_json",
    "lower_structured_loop",
    "require_compiler_contract",
    "settle_workflow_outputs",
    "thaw_json",
    "workflow_ir_public_projection_v1",
]
