#!/usr/bin/env bash
# Bump all application package versions in lockstep.
#
# Usage:
#   scripts/bump_version.sh <version>     # e.g. scripts/bump_version.sh 2.2.0
#
# Updates:
#   backend/pyproject.toml              (version = "...")
#   backend/packages/harness/pyproject.toml (version = "...")
#   frontend/package.json               ("version": "...")
#   backend/uv.lock                     (regenerated by uv)
#
# This does not create a commit, tag, or release artifact. Publication remains
# an explicit operation in the private project's release process.

set -euo pipefail

if [ "$#" -ne 1 ]; then
  echo "Usage: $0 <version>   (e.g. $0 2.2.0)" >&2
  exit 1
fi

VERSION="${1#v}"  # tolerate a leading "v" (tag form) if passed by mistake

if ! printf '%s' "$VERSION" | grep -Eq '^[0-9]+\.[0-9]+\.[0-9]+([0-9A-Za-z.+-]+)?$'; then
  echo "error: '$VERSION' is not a valid SemVer (expected X.Y.Z[, -prerelease])" >&2
  exit 1
fi

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
PYPROJECT="$ROOT/backend/pyproject.toml"
HARNESS_PYPROJECT="$ROOT/backend/packages/harness/pyproject.toml"
PACKAGE="$ROOT/frontend/package.json"
UV_LOCK="$ROOT/backend/uv.lock"

for f in "$PYPROJECT" "$HARNESS_PYPROJECT" "$PACKAGE" "$UV_LOCK"; do
  if [ ! -f "$f" ]; then
    echo "error: expected version file not found: $f" >&2
    exit 1
  fi
done
if ! command -v uv >/dev/null 2>&1; then
  echo "error: uv is required to refresh backend/uv.lock" >&2
  exit 1
fi

BUMP_BACKUP_DIR="$(mktemp -d)"
BUMP_SUCCEEDED=0
cp "$PYPROJECT" "$BUMP_BACKUP_DIR/backend-pyproject.toml"
cp "$HARNESS_PYPROJECT" "$BUMP_BACKUP_DIR/harness-pyproject.toml"
cp "$PACKAGE" "$BUMP_BACKUP_DIR/frontend-package.json"
cp "$UV_LOCK" "$BUMP_BACKUP_DIR/uv.lock"

cleanup_bump() {
  bump_status=$?
  trap - EXIT
  if [ "$BUMP_SUCCEEDED" -ne 1 ]; then
    cp "$BUMP_BACKUP_DIR/backend-pyproject.toml" "$PYPROJECT"
    cp "$BUMP_BACKUP_DIR/harness-pyproject.toml" "$HARNESS_PYPROJECT"
    cp "$BUMP_BACKUP_DIR/frontend-package.json" "$PACKAGE"
    cp "$BUMP_BACKUP_DIR/uv.lock" "$UV_LOCK"
  fi
  rm -rf -- "$BUMP_BACKUP_DIR"
  exit "$bump_status"
}
trap cleanup_bump EXIT

python3 - "$PYPROJECT" "$HARNESS_PYPROJECT" "$PACKAGE" "$VERSION" <<'PY'
import re
import sys

pyproject, harness_pyproject, package, version = sys.argv[1:5]

updates = {}

# Python packages — version = "..."
for path in (pyproject, harness_pyproject):
    with open(path) as f:
        src = f.read()
    new, count = re.subn(
        r'(?m)^version\s*=\s*".*?"',
        f'version = "{version}"',
        src,
        count=1,
    )
    if count != 1:
        sys.exit(f"error: no top-level 'version' field in {path}")
    updates[path] = new

# frontend/package.json — "version": "..." (preserve indentation; minimal diff)
with open(package) as f:
    src = f.read()
new, count = re.subn(
    r'(?m)^(\s*)"version"\s*:\s*".*?"',
    lambda m: f'{m.group(1)}"version": "{version}"',
    src,
    count=1,
)
if count != 1:
    sys.exit(f'error: no top-level "version" field in {package}')
updates[package] = new

# Write only after every source has been parsed successfully.
for path, content in updates.items():
    with open(path, "w") as f:
        f.write(content)
PY

(cd "$ROOT/backend" && uv lock)

echo "Bumped version to $VERSION in:"
echo "  backend/pyproject.toml"
echo "  backend/packages/harness/pyproject.toml"
echo "  frontend/package.json"
echo "  backend/uv.lock"
echo

if ! bash "$ROOT/scripts/verify_versions.sh" "$VERSION"; then
  echo "error: post-bump verification failed." >&2
  exit 1
fi

BUMP_SUCCEEDED=1

echo
echo "Next steps:"
echo "  1. Review the version changes"
echo "  2. Run the release test gates for this checkout"
echo "  3. Commit and tag according to the private release process"
